-- StrainCollector Product Seed Data
-- Run this AFTER schema.sql in Supabase SQL Editor

-- ═══════════════════════════════════════════════════════════════
-- FRESH SNIPS (62 strains)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO products (id, name, slug, category, image_url, in_stock) VALUES
  ('louie-13', 'Louie 13', 'louie-13', 'fresh_snip', '/logo.png', true),
  ('push-pop-sunset-sherb', 'Push Pop / Sunset Sherb', 'push-pop-sunset-sherb', 'fresh_snip', '/strainpics/sunset_sherbet.jpg', true),
  ('pre-98-bubba', 'Pre 98 Bubba', 'pre-98-bubba', 'fresh_snip', '/logo.png', true),
  ('dosidos', 'Dosidos', 'dosidos', 'fresh_snip', '/logo.png', true),
  ('cherry-pie-kush', 'Cherry Pie Kush', 'cherry-pie-kush', 'fresh_snip', '/logo.png', true),
  ('cherry-pie', 'Cherry Pie', 'cherry-pie', 'fresh_snip', '/strainpics/cherry_pie_og.jpg', true),
  ('chem-sister', 'Chem Sister', 'chem-sister', 'fresh_snip', '/logo.png', true),
  ('mango-kush', 'Mango Kush', 'mango-kush', 'fresh_snip', '/logo.png', true),
  ('ghost-og-snip', 'Ghost OG', 'ghost-og-snip', 'fresh_snip', '/strainpics/ghost_og.png', true),
  ('platinum-og', 'Platinum OG', 'platinum-og', 'fresh_snip', '/strainpics/platinum_og.jpg', true),
  ('sfv-og-snip', 'SFV OG', 'sfv-og-snip', 'fresh_snip', '/strainpics/sfv_og.webp', true),
  ('gg4-snip', 'GG4', 'gg4-snip', 'fresh_snip', '/strainpics/gg4.jpg', true),
  ('rainbow-beltz', 'Rainbow Beltz', 'rainbow-beltz', 'fresh_snip', '/strainpics/rainbow_belts.jpg', true),
  ('fruity-pebbles-og', 'Fruity Pebbles OG', 'fruity-pebbles-og', 'fresh_snip', '/strainpics/fruity_pebbles_og.webp', true),
  ('rs11-snip', 'RS11', 'rs11-snip', 'fresh_snip', '/strainpics/rs_11.webp', true),
  ('f1-durban', 'F1 Durban', 'f1-durban', 'fresh_snip', '/strainpics/durban_poison.webp', true),
  ('lemon-tree', 'Lemon Tree', 'lemon-tree', 'fresh_snip', '/logo.png', true),
  ('georgia-pie', 'Georgia Pie', 'georgia-pie', 'fresh_snip', '/strainpics/georgia_pie.webp', true),
  ('cherry-kush', 'Cherry Kush', 'cherry-kush', 'fresh_snip', '/logo.png', true),
  ('purple-urkle', 'Purple Urkle', 'purple-urkle', 'fresh_snip', '/logo.png', true),
  ('animal-cooks', 'Animal Cooks', 'animal-cooks', 'fresh_snip', '/strainpics/animal_cookies.jpg', true),
  ('blue-zushi', 'Blue Zushi', 'blue-zushi', 'fresh_snip', '/strainpics/blue_zushi.webp', true),
  ('government-oasis', 'Government Oasis', 'government-oasis', 'fresh_snip', '/logo.png', true),
  ('gelonade-snip', 'Gelonade', 'gelonade-snip', 'fresh_snip', '/strainpics/gelonade.webp', true),
  ('apple-fritter-snip', 'Apple Fritter', 'apple-fritter-snip', 'fresh_snip', '/strainpics/apple_fritter.jpg', true),
  ('white-truffle-snip', 'White Truffle', 'white-truffle-snip', 'fresh_snip', '/strainpics/white_truffle.webp', true),
  ('animal-face-snip', 'Animal Face', 'animal-face-snip', 'fresh_snip', '/strainpics/animal_face.jpg', true),
  ('sherbanger-x-z', 'Sherbanger x Z', 'sherbanger-x-z', 'fresh_snip', '/logo.png', true),
  ('z-strain', 'Z', 'z-strain', 'fresh_snip', '/logo.png', true),
  ('kush-mints', 'Kush Mints', 'kush-mints', 'fresh_snip', '/strainpics/kush_mints.jpg', true),
  ('apples-and-bananas', 'Apples & Bananas', 'apples-and-bananas', 'fresh_snip', '/strainpics/apples_bananas.jpg', true),
  ('perm-marker', 'Perm Marker', 'perm-marker', 'fresh_snip', '/strainpics/permanent_marker.webp', true),
  ('amnesia-haze-core-cut', 'Amnesia Haze (Core Cut)', 'amnesia-haze-core-cut', 'fresh_snip', '/strainpics/amnesia_hypro.jpg', true),
  ('nl2', 'NL2', 'nl2', 'fresh_snip', '/logo.png', true),
  ('outback-haze-cross', 'Outback Haze x Lemon Skunk x SFV x TK', 'outback-haze-cross', 'fresh_snip', '/logo.png', true),
  ('chem-sister-x-nl2', 'Chem Sister x NL2', 'chem-sister-x-nl2', 'fresh_snip', '/logo.png', true),
  ('g13-double-widow-grape-ape', 'G13 x Double Widow x Grape Ape', 'g13-double-widow-grape-ape', 'fresh_snip', '/logo.png', true),
  ('70s-afghani-x-grape-ape', '70s Afghani x Grape Ape', '70s-afghani-x-grape-ape', 'fresh_snip', '/logo.png', true),
  ('chem-91', 'Chem 91', 'chem-91', 'fresh_snip', '/strainpics/chem_91.jpg', true),
  ('grape-ape', 'Grape Ape', 'grape-ape', 'fresh_snip', '/strainpics/grape_ape.png', true),
  ('cookies-n-chem', 'Cookies N Chem', 'cookies-n-chem', 'fresh_snip', '/strainpics/cookies_chem.webp', true),
  ('albany-sour-diesel', 'Albany Sour Diesel', 'albany-sour-diesel', 'fresh_snip', '/logo.png', true),
  ('daywrecker', 'Daywrecker', 'daywrecker', 'fresh_snip', '/logo.png', true),
  ('irene', 'Irene', 'irene', 'fresh_snip', '/logo.png', true),
  ('black-maple-22', 'Black Maple 22', 'black-maple-22', 'fresh_snip', '/strainpics/black_maple.jpg', true),
  ('illemonatti', 'Illemonatti', 'illemonatti', 'fresh_snip', '/logo.png', true),
  ('golden-ticket', 'Golden Ticket', 'golden-ticket', 'fresh_snip', '/logo.png', true),
  ('glitter-bomb-snip', 'Glitter Bomb', 'glitter-bomb-snip', 'fresh_snip', '/strainpics/glitter_bomb.webp', true),
  ('slapz-snip', 'SLAPZ', 'slapz-snip', 'fresh_snip', '/strainpics/slapz.webp', true),
  ('purple-haze', 'Purple Haze', 'purple-haze', 'fresh_snip', '/logo.png', true),
  ('trop-cherry', 'Trop Cherry', 'trop-cherry', 'fresh_snip', '/strainpics/tropicana_cherry.webp', true),
  ('lavender', 'Lavender', 'lavender', 'fresh_snip', '/strainpics/lavender.jpg', true),
  ('skywalker-2', 'Skywalker 2.0', 'skywalker-2', 'fresh_snip', '/strainpics/skywalker_og.webp', true),
  ('oreoz-snip', 'Oreoz', 'oreoz-snip', 'fresh_snip', '/strainpics/oreoz.webp', true),
  ('santa-cruz-blue-dream', 'Santa Cruz Blue Dream', 'santa-cruz-blue-dream', 'fresh_snip', '/strainpics/blue_dream_santa_cruz.png', true),
  ('mochi', 'Mochi', 'mochi', 'fresh_snip', '/strainpics/mochi.webp', true),
  ('zurge', 'Zurge', 'zurge', 'fresh_snip', '/logo.png', true),
  ('cherry-gushers', 'Cherry Gushers', 'cherry-gushers', 'fresh_snip', '/strainpics/gushers.webp', true),
  ('hollywood-runtz-lcg', 'Hollywood (Runtz x LCG)', 'hollywood-runtz-lcg', 'fresh_snip', '/strainpics/hollywood.png', true),
  ('hollywood-pk-topanga', 'Hollywood PK / Topanga', 'hollywood-pk-topanga', 'fresh_snip', '/logo.png', true),
  ('sherbanger-22', 'Sherbanger 22', 'sherbanger-22', 'fresh_snip', '/strainpics/sherbanger_22.webp', true),
  ('banana-og', 'Banana OG', 'banana-og', 'fresh_snip', '/strainpics/banana_og.webp', true)
ON CONFLICT (id) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════
-- ROOTED CLONES (62 unique strains)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO products (id, name, slug, category, image_url, in_stock) VALUES
  ('artificial-red', 'Artificial Red', 'artificial-red', 'rooted_clone', '/logo.png', true),
  ('animal-face', 'Animal Face', 'animal-face', 'rooted_clone', '/strainpics/animal_face.jpg', true),
  ('apple-fritter', 'Apple Fritter', 'apple-fritter', 'rooted_clone', '/strainpics/apple_fritter.jpg', true),
  ('bdog', 'BDOG', 'bdog', 'rooted_clone', '/logo.png', true),
  ('blue-dream', 'Blue Dream', 'blue-dream', 'rooted_clone', '/strainpics/blue_dream.webp', true),
  ('bubba-kush', 'Bubba Kush', 'bubba-kush', 'rooted_clone', '/strainpics/bubba_kush.webp', true),
  ('cap-junky', 'Cap Junky', 'cap-junky', 'rooted_clone', '/strainpics/cap_junky.jpg', true),
  ('double-runtz', 'Double Runtz', 'double-runtz', 'rooted_clone', '/strainpics/double_runtz.jpg', true),
  ('gelonade', 'Gelonade', 'gelonade', 'rooted_clone', '/strainpics/gelonade.webp', true),
  ('gg4', 'GG4', 'gg4', 'rooted_clone', '/strainpics/gg4.jpg', true),
  ('ghost-og', 'Ghost OG', 'ghost-og', 'rooted_clone', '/strainpics/ghost_og.png', true),
  ('glitterbomb', 'GlitterBomb', 'glitterbomb', 'rooted_clone', '/strainpics/glitter_bomb.webp', true),
  ('green-crack', 'Green Crack', 'green-crack', 'rooted_clone', '/strainpics/green_crack.webp', true),
  ('hollywood', 'Hollywood', 'hollywood', 'rooted_clone', '/strainpics/hollywood.png', true),
  ('london-pound-cake', 'London Pound Cake', 'london-pound-cake', 'rooted_clone', '/strainpics/london_pound_cake.jpg', true),
  ('mimosa', 'Mimosa', 'mimosa', 'rooted_clone', '/strainpics/mimosa.webp', true),
  ('octane-mints', 'Octane Mints', 'octane-mints', 'rooted_clone', '/strainpics/octane_mintz.webp', true),
  ('oreoz', 'Oreoz', 'oreoz', 'rooted_clone', '/strainpics/oreoz.webp', true),
  ('oreo-blizzard', 'Oreo Blizzard', 'oreo-blizzard', 'rooted_clone', '/strainpics/oreo_blizzard.jpg', true),
  ('pink-runtz', 'Pink Runtz', 'pink-runtz', 'rooted_clone', '/strainpics/pink_runtz.png', true),
  ('pure-michigan', 'Pure Michigan', 'pure-michigan', 'rooted_clone', '/strainpics/pure_michigan.jpg', true),
  ('rainbow-belts-3', 'Rainbow Belts 3.0', 'rainbow-belts-3', 'rooted_clone', '/strainpics/rainbow_belts.jpg', true),
  ('rs-11', 'RS-11', 'rs-11', 'rooted_clone', '/strainpics/rs_11.webp', true),
  ('scented-marker', 'Scented Marker', 'scented-marker', 'rooted_clone', '/strainpics/scented_marker.webp', true),
  ('sfv-og', 'SFV OG', 'sfv-og', 'rooted_clone', '/strainpics/sfv_og.webp', true),
  ('slapz', 'SLAPZ', 'slapz', 'rooted_clone', '/strainpics/slapz.webp', true),
  ('snowball', 'Snowball', 'snowball', 'rooted_clone', '/strainpics/snowball.jpg', true),
  ('strawberry-cough', 'Strawberry Cough', 'strawberry-cough', 'rooted_clone', '/strainpics/strawberry_cough.jpg', true),
  ('super-runtz', 'Super Runtz', 'super-runtz', 'rooted_clone', '/strainpics/super_runtz.png', true),
  ('super-lemon-haze', 'Super Lemon Haze', 'super-lemon-haze', 'rooted_clone', '/strainpics/super_lemon_haze.webp', true),
  ('wedding-cake', 'Wedding Cake', 'wedding-cake', 'rooted_clone', '/strainpics/wedding_cake.webp', true),
  ('og-kush', 'OG Kush', 'og-kush', 'rooted_clone', '/logo.png', true),
  ('sharpie', 'Sharpie', 'sharpie', 'rooted_clone', '/logo.png', true),
  ('lipsmacker', 'Lipsmacker', 'lipsmacker', 'rooted_clone', '/logo.png', true),
  ('ice-cream-man', 'Ice Cream Man', 'ice-cream-man', 'rooted_clone', '/strainpics/ice_cream_man.png', true),
  ('blue-zkittles', 'Blue Zkittles', 'blue-zkittles', 'rooted_clone', '/strainpics/blue_zkittles.jpg', true),
  ('rain-maker', 'Rain Maker', 'rain-maker', 'rooted_clone', '/strainpics/rainmaker.jpg', true),
  ('monster-cookies', 'Monster Cookies', 'monster-cookies', 'rooted_clone', '/strainpics/monster_cookies.jpg', true),
  ('gelato-41', 'Gelato 41', 'gelato-41', 'rooted_clone', '/strainpics/gelato_41.png', true),
  ('cereal-milk', 'Cereal Milk', 'cereal-milk', 'rooted_clone', '/strainpics/cereal_milk.jpg', true),
  ('purple-punch', 'Purple Punch', 'purple-punch', 'rooted_clone', '/strainpics/purple_punch.webp', true),
  ('rozay', 'Rozay', 'rozay', 'rooted_clone', '/strainpics/rozay.webp', true),
  ('mac-1', 'Mac 1', 'mac-1', 'rooted_clone', '/strainpics/mac_1.webp', true),
  ('slurricane', 'Slurricane', 'slurricane', 'rooted_clone', '/strainpics/slurricane.webp', true),
  ('platinum-punch', 'Platinum Punch', 'platinum-punch', 'rooted_clone', '/strainpics/platinum_punch.jpg', true),
  ('permanent-marker', 'Permanent Marker', 'permanent-marker', 'rooted_clone', '/strainpics/permanent_marker.webp', true),
  ('lemon-cherry-gelato', 'Lemon Cherry Gelato', 'lemon-cherry-gelato', 'rooted_clone', '/strainpics/lemon_cherry_gelato.jpg', true),
  ('holy-gelato', 'Holy Gelato', 'holy-gelato', 'rooted_clone', '/logo.png', true),
  ('forbidden-fruit', 'Forbidden Fruit', 'forbidden-fruit', 'rooted_clone', '/strainpics/forbidden_fruit.webp', true),
  ('w-runtz', 'W. Runtz', 'w-runtz', 'rooted_clone', '/strainpics/white_runtz.webp', true),
  ('cherry-gas', 'Cherry Gas', 'cherry-gas', 'rooted_clone', '/strainpics/cherry_gas.jpg', true),
  ('super-boof', 'Super Boof', 'super-boof', 'rooted_clone', '/logo.png', true),
  ('white-truffle', 'White Truffle', 'white-truffle', 'rooted_clone', '/strainpics/white_truffle.webp', true),
  ('pure-fire', 'Pure Fire', 'pure-fire', 'rooted_clone', '/logo.png', true),
  ('sour-diesel', 'Sour Diesel', 'sour-diesel', 'rooted_clone', '/strainpics/sour_diesel.webp', true),
  ('super-glue', 'Super Glue', 'super-glue', 'rooted_clone', '/logo.png', true),
  ('skywalker-og', 'Skywalker OG', 'skywalker-og', 'rooted_clone', '/strainpics/skywalker_og.webp', true),
  ('tahoe-kush', 'Tahoe Kush', 'tahoe-kush', 'rooted_clone', '/strainpics/tahoe_og.jpg', true),
  ('wifi-og', 'Wifi OG', 'wifi-og', 'rooted_clone', '/strainpics/wifi_og.jpg', true),
  ('larry-og', 'Larry OG', 'larry-og', 'rooted_clone', '/strainpics/larry_og.jpg', true),
  ('skunk-kush', 'Skunk Kush', 'skunk-kush', 'rooted_clone', '/logo.png', true),
  ('skyberry-og', 'SkyBerry OG', 'skyberry-og', 'rooted_clone', '/logo.png', true)
ON CONFLICT (id) DO NOTHING;
