/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    dealers: DealerAuthOperations;
    users: UserAuthOperations;
    affiliates: AffiliateAuthOperations;
    salesReps: SalesRepAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    dealers: Dealer;
    pages: Page;
    posts: Post;
    products: Product;
    media: Media;
    categories: Category;
    productCategories: ProductCategory;
    users: User;
    customers: Customer;
    orders: Order;
    'discount-tiers': DiscountTier;
    'bulk-discount-levels': BulkDiscountLevel;
    'discount-codes': DiscountCode;
    affiliates: Affiliate;
    'shipping-config': ShippingConfig;
    'shipping-carriers': ShippingCarrier;
    'shipping-rate-cache': ShippingRateCache;
    'stealth-events': StealthEvent;
    salesReps: SalesRep;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'discount-tiers': DiscountTiersSelect<false> | DiscountTiersSelect<true>;
    'bulk-discount-levels': BulkDiscountLevelsSelect<false> | BulkDiscountLevelsSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    affiliates: AffiliatesSelect<false> | AffiliatesSelect<true>;
    'shipping-config': ShippingConfigSelect<false> | ShippingConfigSelect<true>;
    'shipping-carriers': ShippingCarriersSelect<false> | ShippingCarriersSelect<true>;
    'shipping-rate-cache': ShippingRateCacheSelect<false> | ShippingRateCacheSelect<true>;
    'stealth-events': StealthEventsSelect<false> | StealthEventsSelect<true>;
    salesReps: SalesRepsSelect<false> | SalesRepsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user:
    | (Admin & {
        collection: 'admins';
      })
    | (Dealer & {
        collection: 'dealers';
      })
    | (User & {
        collection: 'users';
      })
    | (Affiliate & {
        collection: 'affiliates';
      })
    | (SalesRep & {
        collection: 'salesReps';
      });
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface DealerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AffiliateAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface SalesRepAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Dealers who can access special pricing and features
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  companyName: string;
  /**
   * Name of the primary contact for this dealer account
   */
  contactName: string;
  phoneNumber: string;
  address: {
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    zip: string;
  };
  /**
   * Check this if shipping address is different from billing address
   */
  useShippingAddress?: boolean | null;
  shippingAddress?: {
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    zip: string;
  };
  /**
   * Upload tax exemption certificates and related documents
   */
  taxExemptDocuments?:
    | {
        document: number | Media;
        type: 'resale' | 'exemption' | 'other';
        /**
         * When does this document expire? (if applicable)
         */
        expirationDate?: string | null;
        /**
         * Any additional notes about this document
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Current status of tax exemption application
   */
  taxExemptStatus?: ('none' | 'pending' | 'approved' | 'rejected') | null;
  /**
   * Internal notes about tax exempt status
   */
  taxExemptNotes?: string | null;
  /**
   * Automatically generated from address
   */
  coordinates: {
    latitude: number;
    longitude: number;
  };
  /**
   * Define the service coverage area for this dealer
   */
  serviceArea: {
    radius: number;
    willTravel?: boolean | null;
    /**
     * Additional notes about service area or travel capabilities
     */
    travelNotes?: string | null;
  };
  /**
   * Has this dealer been verified by an admin?
   */
  verified?: boolean | null;
  /**
   * The discount tier for this dealer
   */
  discountTier?: (number | null) | DiscountTier;
  /**
   * The sales representative assigned to this dealer
   */
  salesRep?: (number | null) | SalesRep;
  /**
   * Complete history of sales rep assignments for this dealer
   */
  salesRepAssignmentHistory?:
    | {
        /**
         * The sales representative for this assignment period
         */
        salesRep: number | SalesRep;
        /**
         * When this dealer was assigned to this sales rep
         */
        assignedAt: string;
        /**
         * When this assignment ended (null if current assignment)
         */
        unassignedAt?: string | null;
        /**
         * Admin who made this assignment
         */
        assignedBy?: (number | null) | User;
        /**
         * Optional notes about this assignment
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Is this dealer exempt from paying tax?
   */
  taxExempt?: boolean | null;
  /**
   * Force the dealer to change their password on next login
   */
  forcePasswordChange?: boolean | null;
  /**
   * Custom shipping options for this dealer
   */
  customShipping?: {
    /**
     * If checked, this dealer always gets free shipping.
     */
    hasFreeShipping?: boolean | null;
    /**
     * If set, this dealer will be charged this shipping price instead of UPS rates.
     */
    customPrice?: number | null;
  };
  /**
   * Set a fixed price or discount for specific products for this dealer. Only one of Fixed Price or Discount (%) can be set per product.
   */
  customPrices?:
    | {
        /**
         * A descriptive name for this custom price (e.g., "Bulk Order Discount", "VIP Customer Rate", etc.)
         */
        name: string;
        product: number | Product;
        /**
         * Set a fixed price for this product (cannot be used with discount %)
         */
        fixedPrice?: number | null;
        /**
         * Set a discount percentage for this product (cannot be used with fixed price)
         */
        discountPercent?: number | null;
        /**
         * Admin who created this custom price (autopopulated on save)
         */
        createdBy?: (number | null) | User;
        /**
         * When this custom price was created (autopopulated on save)
         */
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage dealer discount tiers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-tiers".
 */
export interface DiscountTier {
  id: number;
  /**
   * Name of the discount tier (e.g. Standard, Premium, Elite)
   */
  name: string;
  /**
   * Base percentage discount for this tier (0-100, optional)
   */
  discountPercentage?: number | null;
  /**
   * Order subtotal threshold for additional volume discount ($, optional)
   */
  volumeDiscountThreshold?: number | null;
  /**
   * Additional percentage discount when order exceeds threshold (0-100, optional)
   */
  volumeDiscountPercentage?: number | null;
  /**
   * Description of this discount tier and its benefits
   */
  description?: string | null;
  /**
   * Whether this discount tier is currently active
   */
  active?: boolean | null;
  /**
   * Custom shipping options for this discount tier
   */
  customShipping?: {
    /**
     * If checked, all dealers in this tier get free shipping.
     */
    hasFreeShipping?: boolean | null;
    /**
     * If set, all dealers in this tier will be charged this shipping price instead of UPS rates.
     */
    customPrice?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Sales representatives who can access dealer orders and commissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "salesReps".
 */
export interface SalesRep {
  id: number;
  /**
   * Full name of the sales representative
   */
  name: string;
  /**
   * Role/position of the sales representative
   */
  role?: ('rep' | 'senior_rep' | 'junior_rep' | 'manager' | 'regional_manager' | 'director') | null;
  /**
   * Commission rate as a percentage (0-100)
   */
  commissionRate: number;
  /**
   * Monthly/quarterly sales goal (optional)
   */
  targetQuota?: number | null;
  /**
   * How commission should be calculated for this sales rep
   */
  commissionCalculationMethod: 'all_orders' | 'completed_orders';
  /**
   * Whether this sales rep can access the system
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Admin users who can access the admin panel
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Can this user access the admin panel?
   */
  canAccessAdmin: boolean;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Display Name for customer-facing product cards. Leave empty to use the main title.
   */
  displayName?: string | null;
  /**
   * Secondary display text for product cards (e.g., shown above or below the image).
   */
  subtitle?: string | null;
  /**
   * The date when this product will be available for purchase. Set to a past date for currently available products.
   */
  releaseDate: string;
  /**
   * General product description that applies to all product types
   */
  description?: string | null;
  productType: 'battery' | 'accessory' | 'swag';
  /**
   * Select the type of swag item
   */
  swagType?: ('apparel' | 'hat' | 'sticker' | 'other') | null;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Select product categories
   */
  productCategories?: (number | ProductCategory)[] | null;
  /**
   * Legacy categories - please use product categories instead
   */
  legacyCategories?: (number | Category)[] | null;
  price: number;
  /**
   * Dealer Price - The price dealers pay for this product
   */
  dealerPrice: number;
  /**
   * Original price for showing discounts
   */
  compareAtPrice?: number | null;
  inventory: {
    trackInventory?: boolean | null;
    quantity: number;
    lowStockThreshold?: number | null;
  };
  variants?:
    | {
        name: string;
        options?:
          | {
              value: string;
              priceAdjustment?: number | null;
              inventory?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The model number of the product
   */
  modelNumber?: string | null;
  /**
   * Product shipping dimensions and weight
   */
  shippingDetails: {
    /**
     * Weight in pounds
     */
    weight: number;
    /**
     * Length in inches
     */
    length: number;
    /**
     * Width in inches
     */
    width: number;
    /**
     * Height in inches
     */
    height: number;
    /**
     * NMFC freight class (for LTL shipments)
     */
    freightClass?:
      | (
          | '50'
          | '55'
          | '60'
          | '65'
          | '70'
          | '77.5'
          | '85'
          | '92.5'
          | '100'
          | '110'
          | '125'
          | '150'
          | '175'
          | '200'
          | '250'
          | '300'
          | '400'
          | '500'
        )
      | null;
    /**
     * Requires liftgate for delivery
     */
    requiresLiftgate?: boolean | null;
    /**
     * Can this product be stacked during shipping?
     */
    stackable?: boolean | null;
    /**
     * Is this a hazardous material?
     */
    hazmat?: boolean | null;
    /**
     * Custom packaging dimensions (if different from product)
     */
    customPackaging?: {
      /**
       * Use custom packaging dimensions
       */
      useCustom?: boolean | null;
      /**
       * Package length in inches
       */
      packageLength?: number | null;
      /**
       * Package width in inches
       */
      packageWidth?: number | null;
      /**
       * Package height in inches
       */
      packageHeight?: number | null;
      /**
       * Additional package weight in pounds
       */
      packageWeight?: number | null;
    };
    /**
     * Additional shipping notes or special handling instructions
     */
    shippingNotes?: string | null;
  };
  heroImage?: (number | null) | Media;
  /**
   * Mascot image for the battery line (e.g. Strykerfish)
   */
  batteryMascot?: (number | null) | Media;
  /**
   * Add multiple images to the product gallery
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  specifications?: {
    /**
     * Type of battery (e.g. Lithium Iron Phosphate)
     */
    batteryType?: string | null;
    /**
     * The product line this battery belongs to (e.g. Kraken)
     */
    modelFamily?: string | null;
    grade?: ('A' | 'B' | 'C') | null;
    purpose?: ('dual' | 'starting' | 'deepCycle') | null;
    /**
     * Amp Hours (e.g. 135Ah)
     */
    ampHours?: number | null;
    /**
     * Watt Hours (e.g. 1728Wh)
     */
    wattHours?: number | null;
    voltage?: {
      /**
       * Displayed/Advertised Voltage (e.g. 12V, 24V, 36V)
       */
      displayedVoltage?: number | null;
      /**
       * Standard Voltage (e.g. 12.8V)
       */
      standard?: number | null;
      /**
       * Charging Voltage (e.g. 14.6V)
       */
      charging?: number | null;
    };
    current?: {
      /**
       * Maximum Charging Current (e.g. 100A)
       */
      maxChargingCurrent?: number | null;
      /**
       * Maximum Continuous Discharge Current (e.g. 200A)
       */
      maxContinuousDischarge?: number | null;
      /**
       * Cold Cranking Amps (e.g. 1200A)
       */
      coldCranking?: number | null;
    };
    dimensions?: {
      /**
       * Length in inches
       */
      length?: number | null;
      /**
       * Width in inches
       */
      width?: number | null;
      /**
       * Height in inches
       */
      height?: number | null;
    };
    /**
     * Weight in pounds
     */
    weight?: number | null;
    /**
     * Number of cycles (e.g. 6000)
     */
    cycles?: number | null;
    hasBluetoothConnectivity?: boolean | null;
    /**
     * Maximum operating temperature in Fahrenheit (e.g. 140)
     */
    maxTemperature?: number | null;
  };
  accessoryDetails?: {
    accessoryType?: ('charger' | 'monitor' | 'cable' | 'mount' | 'tool' | 'other') | null;
    /**
     * What battery models or systems this accessory is compatible with
     */
    compatibility?: string | null;
    /**
     * Key specifications or features of the accessory
     */
    specifications?: string | null;
    dimensions?: {
      length?: number | null;
      width?: number | null;
      height?: number | null;
    };
    weight?: number | null;
  };
  swagDetails?: {
    /**
     * Material composition (e.g. 100% Cotton)
     */
    material?: string | null;
    careInstructions?: string | null;
    fit?: ('regular' | 'slim' | 'relaxed') | null;
    dimensions?: {
      width?: number | null;
      height?: number | null;
    };
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Select related products
   */
  relatedProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  /**
   * Lower numbers appear first (e.g. 0 for batteries, 1 for accessories, 2 for swag)
   */
  order: number;
  /**
   * Select a product to feature for this category. This product's image will be displayed on the main products page as the category preview.
   */
  featuredProduct?: (number | null) | Product;
  parent?: (number | null) | ProductCategory;
  breadcrumbs?:
    | {
        doc?: (number | null) | ProductCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  /**
   * Full name (used for Stripe)
   */
  name?: string | null;
  /**
   * First name (for internal use)
   */
  firstName?: string | null;
  /**
   * Last name (for internal use)
   */
  lastName?: string | null;
  /**
   * The Stripe Customer ID associated with this customer
   */
  stripeCustomerId: string;
  /**
   * Customer phone number
   */
  phone?: string | null;
  shippingAddresses?:
    | {
        /**
         * Full name for shipping
         */
        name: string;
        firstName: string;
        lastName: string;
        line1: string;
        line2?: string | null;
        city: string;
        state: string;
        postalCode: string;
        country: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  billingAddresses?:
    | {
        /**
         * Full name for billing
         */
        name: string;
        firstName: string;
        lastName: string;
        line1: string;
        line2?: string | null;
        city: string;
        state: string;
        postalCode: string;
        country: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stripeID?: string | null;
  skipSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Secure UUID for public order identification
   */
  uuid: string;
  /**
   * Automatically generated sequential order number
   */
  orderNumber?: number | null;
  customer: number | Customer;
  /**
   * The dealer who placed this order (if applicable)
   */
  dealer?: (number | null) | Dealer;
  /**
   * The affiliate who referred this order (if applicable)
   */
  affiliate?: (number | null) | Affiliate;
  items: {
    /**
     * Product reference
     */
    product: number | Product;
    title: string;
    quantity: number;
    price: number;
    variant?: {
      name?: string | null;
      value?: string | null;
    };
    id?: string | null;
  }[];
  subtotal: number;
  tax: number;
  /**
   * Indicates if this order is exempt from tax (e.g. for dealers)
   */
  taxExempt?: boolean | null;
  /**
   * Indicates if this is a dropship order (shipped directly to customer)
   */
  isDropship?: boolean | null;
  shipping: number;
  /**
   * The selected UPS shipping service code
   */
  shippingService?: string | null;
  /**
   * Main shipment tracking number
   */
  trackingNumber?: string | null;
  /**
   * Individual package tracking numbers and labels
   */
  packageTrackingNumbers?:
    | {
        number: string;
        /**
         * Base64-encoded shipping label image
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When the order was shipped
   */
  shippedAt?: string | null;
  total: number;
  /**
   * Total based on Dealer Price of all items
   */
  dealerTotal?: number | null;
  /**
   * Order status
   */
  status: 'pre-order' | 'back-order' | 'pending' | 'processing' | 'completed' | 'cancelled' | 'refunded';
  /**
   * The Stripe Payment Intent ID associated with this order
   */
  stripePaymentIntentId: string;
  discounts?: {
    dealer?: {
      percentage?: number | null;
      tierId?: number | null;
      tierName?: string | null;
      amount?: number | null;
      volumeDiscountApplied?: boolean | null;
      volumeDiscountThreshold?: number | null;
      volumeDiscountPercentage?: number | null;
      volumeDiscountAmount?: number | null;
    };
    affiliate?: {
      code?: string | null;
      percentage?: number | null;
      amount?: number | null;
      commission?: number | null;
    };
    discountCode?: {
      code?: string | null;
      type?: ('percentage' | 'fixed') | null;
      amount?: number | null;
    };
  };
  shippingAddress: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
  };
  billingAddress: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Affiliate partners who can earn commission through referrals
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates".
 */
export interface Affiliate {
  id: number;
  /**
   * Full name of the affiliate
   */
  name: string;
  /**
   * Optional company or business name
   */
  companyName?: string | null;
  /**
   * Contact phone number
   */
  phoneNumber: string;
  /**
   * Unique affiliate code (automatically generated)
   */
  affiliateCode?: string | null;
  /**
   * Percentage commission the affiliate receives (default 10%)
   */
  affiliateCommission: number;
  /**
   * Percentage discount customers receive using this affiliate code (default 15%)
   */
  customerDiscount: number;
  /**
   * Has this affiliate been verified by an admin?
   */
  verified?: boolean | null;
  /**
   * Payment information for affiliate commissions
   */
  payoutInfo: {
    /**
     * Preferred payment method for commissions
     */
    paymentMethod: 'stripe' | 'paypal' | 'bank';
    /**
     * Stripe Connect account ID
     */
    stripeAccountId?: string | null;
    /**
     * Whether Stripe onboarding has been completed
     */
    stripeOnboardingComplete?: boolean | null;
    /**
     * PayPal email for commission payments
     */
    paypalEmail?: string | null;
    /**
     * Bank name for direct deposit
     */
    bankName?: string | null;
    /**
     * Bank account number
     */
    accountNumber?: string | null;
    /**
     * Bank routing number
     */
    routingNumber?: string | null;
  };
  /**
   * Temporary Stripe Connect onboarding URL
   */
  stripeConnectURL?: string | null;
  /**
   * Total earnings from affiliate commissions
   */
  totalEarnings?: number | null;
  /**
   * Total number of orders through this affiliate
   */
  totalOrders?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Manage bulk pricing discount levels by cart subtotal
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulk-discount-levels".
 */
export interface BulkDiscountLevel {
  id: number;
  /**
   * Label for this discount level (e.g. $20k+ Extra 5%) - This will be displayed in the cart and checkout and also used to identify this bulk discount
   */
  name: string;
  /**
   * Cart subtotal threshold ($) to trigger this discount
   */
  threshold: number;
  /**
   * Percentage discount applied when threshold is met (0-100)
   */
  discountPercent: number;
  /**
   * Optional description for this discount level
   */
  description?: string | null;
  /**
   * Whether this discount level is currently active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage store discount codes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: number;
  /**
   * The discount code (case-sensitive)
   */
  code: string;
  /**
   * Email address this discount code is restricted to (optional)
   */
  email?: string | null;
  /**
   * Type of discount to apply
   */
  discountType: 'percentage' | 'fixed';
  /**
   * Amount of discount (percentage or fixed dollar amount, optional)
   */
  discountAmount?: number | null;
  /**
   * Maximum number of times this code can be used
   */
  maxUses: number;
  /**
   * Number of times this code has been used in completed orders
   */
  totalUses: number;
  /**
   * Number of times this code is currently in active carts (editable)
   */
  pendingUses: number;
  /**
   * Whether this discount code is currently active
   */
  active?: boolean | null;
  /**
   * When this discount code becomes valid (optional)
   */
  validFrom?: string | null;
  /**
   * When this discount code expires (optional)
   */
  validUntil?: string | null;
  /**
   * Custom shipping options for this discount code
   */
  customShipping?: {
    /**
     * If checked, this code grants free shipping.
     */
    hasFreeShipping?: boolean | null;
    /**
     * If set, this code grants this shipping price instead of UPS rates.
     */
    customPrice?: number | null;
  };
  /**
   * If set, this discount code only applies to these products. Otherwise, it applies to the entire cart subtotal.
   */
  applicableProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure shipping rules and costs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-config".
 */
export interface ShippingConfig {
  id: number;
  /**
   * Name of this shipping configuration (e.g. "Standard Shipping Rules")
   */
  name: string;
  /**
   * Only one configuration can be active at a time
   */
  isActive?: boolean | null;
  /**
   * Order amount at which shipping becomes free (0 for never free)
   */
  freeShippingThreshold: number;
  /**
   * Flat rate shipping cost for orders below the free shipping threshold
   */
  flatRateAmount: number;
  /**
   * States where this shipping configuration does not apply
   */
  excludedStates?:
    | {
        state:
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY';
        /**
         * Optional reason for excluding this state
         */
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Any additional notes or special conditions for this shipping configuration
   */
  additionalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure shipping carrier integrations (UPS, FedEx, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-carriers".
 */
export interface ShippingCarrier {
  id: number;
  /**
   * Name of this carrier configuration (e.g. "UPS Production")
   */
  name: string;
  /**
   * Select the shipping carrier
   */
  carrier: 'ups' | 'fedex';
  /**
   * Only one configuration per carrier can be active at a time
   */
  isActive?: boolean | null;
  /**
   * API environment
   */
  environment: 'test' | 'production';
  /**
   * UPS API Configuration
   */
  upsConfig?: {
    credentials: {
      /**
       * UPS API Access Key
       */
      accessKey: string;
      /**
       * UPS User ID
       */
      userId: string;
      /**
       * UPS Password
       */
      password: string;
      /**
       * UPS Account Number
       */
      accountNumber: string;
    };
    services?: {
      ground?: {
        /**
         * Enable UPS Ground
         */
        enabled?: boolean | null;
        /**
         * UPS Ground service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
      threeDaySelect?: {
        /**
         * Enable UPS 3 Day Select
         */
        enabled?: boolean | null;
        /**
         * UPS 3 Day Select service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
      secondDayAir?: {
        /**
         * Enable UPS 2nd Day Air
         */
        enabled?: boolean | null;
        /**
         * UPS 2nd Day Air service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
      nextDayAir?: {
        /**
         * Enable UPS Next Day Air
         */
        enabled?: boolean | null;
        /**
         * UPS Next Day Air service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
    };
  };
  /**
   * FedEx API Configuration
   */
  fedexConfig?: {
    credentials: {
      /**
       * FedEx API Key
       */
      apiKey: string;
      /**
       * FedEx Secret Key
       */
      secretKey: string;
      /**
       * FedEx Account Number
       */
      accountNumber: string;
      /**
       * FedEx Meter Number
       */
      meterNumber: string;
    };
    services?: {
      ground?: {
        /**
         * Enable FedEx Ground
         */
        enabled?: boolean | null;
        /**
         * FedEx Ground service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
      express?: {
        /**
         * Enable FedEx Express Saver
         */
        enabled?: boolean | null;
        /**
         * FedEx Express service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
      twoDayAir?: {
        /**
         * Enable FedEx 2 Day
         */
        enabled?: boolean | null;
        /**
         * FedEx 2 Day service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
      priorityOvernight?: {
        /**
         * Enable FedEx Priority Overnight
         */
        enabled?: boolean | null;
        /**
         * FedEx Priority Overnight service code
         */
        code?: string | null;
        /**
         * Percentage markup on this service
         */
        markup?: number | null;
      };
    };
  };
  /**
   * LTL Freight-specific settings
   */
  ltlSettings?: {
    /**
     * Enable LTL freight shipping
     */
    enableLTL?: boolean | null;
    /**
     * Order weight (lbs) at which to switch to LTL shipping
     */
    ltlThreshold?: number | null;
    /**
     * Default NMFC freight class for LTL shipments
     */
    freightClass?:
      | (
          | '50'
          | '55'
          | '60'
          | '65'
          | '70'
          | '77.5'
          | '85'
          | '92.5'
          | '100'
          | '110'
          | '125'
          | '150'
          | '175'
          | '200'
          | '250'
          | '300'
          | '400'
          | '500'
        )
      | null;
    /**
     * Percentage markup on LTL shipments
     */
    markup?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cached shipping rates to minimize API calls
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-rate-cache".
 */
export interface ShippingRateCache {
  id: number;
  /**
   * Unique key for this rate calculation
   */
  cacheKey: string;
  carrier: 'ups' | 'fedex';
  origin: {
    postalCode: string;
    stateCode: string;
    countryCode: string;
  };
  destination: {
    postalCode: string;
    stateCode: string;
    countryCode: string;
  };
  packageDetails: {
    weight: number;
    length: number;
    width: number;
    height: number;
    isLTL?: boolean | null;
    freightClass?: string | null;
  };
  rates: {
    service: string;
    serviceCode: string;
    rate: number;
    transitDays?: number | null;
    guaranteedDelivery?: boolean | null;
    id?: string | null;
  }[];
  createdAt: string;
  /**
   * When this cached rate expires
   */
  expiresAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stealth-events".
 */
export interface StealthEvent {
  id: number;
  title: string;
  subtitle: string;
  /**
   * When does this event start? (Times are in Phoenix/Arizona timezone)
   */
  eventStartDate?: string | null;
  /**
   * When does this event end? (Times are in Phoenix/Arizona timezone)
   */
  eventEndDate?: string | null;
  mainContent: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. If not provided, it will be automatically generated from the main content.
   */
  excerpt?: string | null;
  mainImage: number | Media;
  secondaryImage: number | Media;
  secondaryHeader: string;
  secondarySubtitle: string;
  slug?: string | null;
  slugLock?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'products';
        value: number | Product;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  price?: number | null;
  modelNumber?: string | null;
  productType?: string | null;
  shippingDetails?: {
    weight?: number | null;
    length?: number | null;
    width?: number | null;
    height?: number | null;
    stackable?: boolean | null;
    hazmat?: boolean | null;
    freightClass?: string | null;
    requiresLiftgate?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'discount-tiers';
        value: number | DiscountTier;
      } | null)
    | ({
        relationTo: 'bulk-discount-levels';
        value: number | BulkDiscountLevel;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'affiliates';
        value: number | Affiliate;
      } | null)
    | ({
        relationTo: 'shipping-config';
        value: number | ShippingConfig;
      } | null)
    | ({
        relationTo: 'shipping-carriers';
        value: number | ShippingCarrier;
      } | null)
    | ({
        relationTo: 'shipping-rate-cache';
        value: number | ShippingRateCache;
      } | null)
    | ({
        relationTo: 'stealth-events';
        value: number | StealthEvent;
      } | null)
    | ({
        relationTo: 'salesReps';
        value: number | SalesRep;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'dealers';
        value: number | Dealer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'affiliates';
        value: number | Affiliate;
      }
    | {
        relationTo: 'salesReps';
        value: number | SalesRep;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'dealers';
        value: number | Dealer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'affiliates';
        value: number | Affiliate;
      }
    | {
        relationTo: 'salesReps';
        value: number | SalesRep;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  companyName?: T;
  contactName?: T;
  phoneNumber?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  useShippingAddress?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  taxExemptDocuments?:
    | T
    | {
        document?: T;
        type?: T;
        expirationDate?: T;
        notes?: T;
        id?: T;
      };
  taxExemptStatus?: T;
  taxExemptNotes?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  serviceArea?:
    | T
    | {
        radius?: T;
        willTravel?: T;
        travelNotes?: T;
      };
  verified?: T;
  discountTier?: T;
  salesRep?: T;
  salesRepAssignmentHistory?:
    | T
    | {
        salesRep?: T;
        assignedAt?: T;
        unassignedAt?: T;
        assignedBy?: T;
        notes?: T;
        id?: T;
      };
  taxExempt?: T;
  forcePasswordChange?: T;
  customShipping?:
    | T
    | {
        hasFreeShipping?: T;
        customPrice?: T;
      };
  customPrices?:
    | T
    | {
        name?: T;
        product?: T;
        fixedPrice?: T;
        discountPercent?: T;
        createdBy?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  displayName?: T;
  subtitle?: T;
  releaseDate?: T;
  description?: T;
  productType?: T;
  swagType?: T;
  slug?: T;
  slugLock?: T;
  productCategories?: T;
  legacyCategories?: T;
  price?: T;
  dealerPrice?: T;
  compareAtPrice?: T;
  inventory?:
    | T
    | {
        trackInventory?: T;
        quantity?: T;
        lowStockThreshold?: T;
      };
  variants?:
    | T
    | {
        name?: T;
        options?:
          | T
          | {
              value?: T;
              priceAdjustment?: T;
              inventory?: T;
              id?: T;
            };
        id?: T;
      };
  modelNumber?: T;
  shippingDetails?:
    | T
    | {
        weight?: T;
        length?: T;
        width?: T;
        height?: T;
        freightClass?: T;
        requiresLiftgate?: T;
        stackable?: T;
        hazmat?: T;
        customPackaging?:
          | T
          | {
              useCustom?: T;
              packageLength?: T;
              packageWidth?: T;
              packageHeight?: T;
              packageWeight?: T;
            };
        shippingNotes?: T;
      };
  heroImage?: T;
  batteryMascot?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        batteryType?: T;
        modelFamily?: T;
        grade?: T;
        purpose?: T;
        ampHours?: T;
        wattHours?: T;
        voltage?:
          | T
          | {
              displayedVoltage?: T;
              standard?: T;
              charging?: T;
            };
        current?:
          | T
          | {
              maxChargingCurrent?: T;
              maxContinuousDischarge?: T;
              coldCranking?: T;
            };
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        weight?: T;
        cycles?: T;
        hasBluetoothConnectivity?: T;
        maxTemperature?: T;
      };
  accessoryDetails?:
    | T
    | {
        accessoryType?: T;
        compatibility?: T;
        specifications?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        weight?: T;
      };
  swagDetails?:
    | T
    | {
        material?: T;
        careInstructions?: T;
        fit?: T;
        dimensions?:
          | T
          | {
              width?: T;
              height?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  relatedProducts?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  featuredProduct?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  canAccessAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  firstName?: T;
  lastName?: T;
  stripeCustomerId?: T;
  phone?: T;
  shippingAddresses?:
    | T
    | {
        name?: T;
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  billingAddresses?:
    | T
    | {
        name?: T;
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  stripeID?: T;
  skipSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  uuid?: T;
  orderNumber?: T;
  customer?: T;
  dealer?: T;
  affiliate?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        quantity?: T;
        price?: T;
        variant?:
          | T
          | {
              name?: T;
              value?: T;
            };
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  taxExempt?: T;
  isDropship?: T;
  shipping?: T;
  shippingService?: T;
  trackingNumber?: T;
  packageTrackingNumbers?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  shippedAt?: T;
  total?: T;
  dealerTotal?: T;
  status?: T;
  stripePaymentIntentId?: T;
  discounts?:
    | T
    | {
        dealer?:
          | T
          | {
              percentage?: T;
              tierId?: T;
              tierName?: T;
              amount?: T;
              volumeDiscountApplied?: T;
              volumeDiscountThreshold?: T;
              volumeDiscountPercentage?: T;
              volumeDiscountAmount?: T;
            };
        affiliate?:
          | T
          | {
              code?: T;
              percentage?: T;
              amount?: T;
              commission?: T;
            };
        discountCode?:
          | T
          | {
              code?: T;
              type?: T;
              amount?: T;
            };
      };
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-tiers_select".
 */
export interface DiscountTiersSelect<T extends boolean = true> {
  name?: T;
  discountPercentage?: T;
  volumeDiscountThreshold?: T;
  volumeDiscountPercentage?: T;
  description?: T;
  active?: T;
  customShipping?:
    | T
    | {
        hasFreeShipping?: T;
        customPrice?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulk-discount-levels_select".
 */
export interface BulkDiscountLevelsSelect<T extends boolean = true> {
  name?: T;
  threshold?: T;
  discountPercent?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  email?: T;
  discountType?: T;
  discountAmount?: T;
  maxUses?: T;
  totalUses?: T;
  pendingUses?: T;
  active?: T;
  validFrom?: T;
  validUntil?: T;
  customShipping?:
    | T
    | {
        hasFreeShipping?: T;
        customPrice?: T;
      };
  applicableProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates_select".
 */
export interface AffiliatesSelect<T extends boolean = true> {
  name?: T;
  companyName?: T;
  phoneNumber?: T;
  affiliateCode?: T;
  affiliateCommission?: T;
  customerDiscount?: T;
  verified?: T;
  payoutInfo?:
    | T
    | {
        paymentMethod?: T;
        stripeAccountId?: T;
        stripeOnboardingComplete?: T;
        paypalEmail?: T;
        bankName?: T;
        accountNumber?: T;
        routingNumber?: T;
      };
  stripeConnectURL?: T;
  totalEarnings?: T;
  totalOrders?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-config_select".
 */
export interface ShippingConfigSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  freeShippingThreshold?: T;
  flatRateAmount?: T;
  excludedStates?:
    | T
    | {
        state?: T;
        reason?: T;
        id?: T;
      };
  additionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-carriers_select".
 */
export interface ShippingCarriersSelect<T extends boolean = true> {
  name?: T;
  carrier?: T;
  isActive?: T;
  environment?: T;
  upsConfig?:
    | T
    | {
        credentials?:
          | T
          | {
              accessKey?: T;
              userId?: T;
              password?: T;
              accountNumber?: T;
            };
        services?:
          | T
          | {
              ground?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
              threeDaySelect?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
              secondDayAir?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
              nextDayAir?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
            };
      };
  fedexConfig?:
    | T
    | {
        credentials?:
          | T
          | {
              apiKey?: T;
              secretKey?: T;
              accountNumber?: T;
              meterNumber?: T;
            };
        services?:
          | T
          | {
              ground?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
              express?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
              twoDayAir?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
              priorityOvernight?:
                | T
                | {
                    enabled?: T;
                    code?: T;
                    markup?: T;
                  };
            };
      };
  ltlSettings?:
    | T
    | {
        enableLTL?: T;
        ltlThreshold?: T;
        freightClass?: T;
        markup?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-rate-cache_select".
 */
export interface ShippingRateCacheSelect<T extends boolean = true> {
  cacheKey?: T;
  carrier?: T;
  origin?:
    | T
    | {
        postalCode?: T;
        stateCode?: T;
        countryCode?: T;
      };
  destination?:
    | T
    | {
        postalCode?: T;
        stateCode?: T;
        countryCode?: T;
      };
  packageDetails?:
    | T
    | {
        weight?: T;
        length?: T;
        width?: T;
        height?: T;
        isLTL?: T;
        freightClass?: T;
      };
  rates?:
    | T
    | {
        service?: T;
        serviceCode?: T;
        rate?: T;
        transitDays?: T;
        guaranteedDelivery?: T;
        id?: T;
      };
  createdAt?: T;
  expiresAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stealth-events_select".
 */
export interface StealthEventsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  eventStartDate?: T;
  eventEndDate?: T;
  mainContent?: T;
  excerpt?: T;
  mainImage?: T;
  secondaryImage?: T;
  secondaryHeader?: T;
  secondarySubtitle?: T;
  slug?: T;
  slugLock?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "salesReps_select".
 */
export interface SalesRepsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  commissionRate?: T;
  targetQuota?: T;
  commissionCalculationMethod?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  price?: T;
  modelNumber?: T;
  productType?: T;
  shippingDetails?:
    | T
    | {
        weight?: T;
        length?: T;
        width?: T;
        height?: T;
        stackable?: T;
        hazmat?: T;
        freightClass?: T;
        requiresLiftgate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}