<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Redline.Calibration.Domain\Redline.Calibration.Domain.csproj" />
    <ProjectReference Include="..\Redline.Calibration.Binary\Redline.Calibration.Binary.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
