using System.Text.RegularExpressions;

namespace Redline.Calibration.Definitions.Xdf;

internal static partial class XdfDefinitionIntelligence
{
    public static IReadOnlyList<XdfTableDefinition> Classify(IReadOnlyList<XdfTableDefinition> source)
    {
        var axisOwners = BuildAxisOwners(source);
        var addressGroups = source
            .Where(table => table.ZAxis.Address.HasValue)
            .GroupBy(table => table.ZAxis.Address!.Value)
            .ToDictionary(group => group.Key, group => group.OrderBy(table => table.SourceIndex).ToArray());

        var classified = new XdfTableDefinition[source.Count];
        for (var index = 0; index < source.Count; index++)
        {
            var table = source[index];
            var evidence = new List<string>();
            var parents = table.ZAxis.Address.HasValue && axisOwners.TryGetValue(table.ZAxis.Address.Value, out var owners)
                ? owners.Select(owner => owner.Table.Id).Distinct(StringComparer.Ordinal).ToArray()
                : Array.Empty<string>();
            var addressGroup = table.ZAxis.Address.HasValue && addressGroups.TryGetValue(table.ZAxis.Address.Value, out var foundGroup)
                ? foundGroup
                : Array.Empty<XdfTableDefinition>();
            var aliases = addressGroup
                .Where(candidate => candidate.Id != table.Id)
                .Select(candidate => candidate.Id)
                .ToArray();

            var role = parents.Length > 0 || AutoGeneratedAxisTitle().IsMatch(table.Title)
                ? XdfTableRole.BreakpointAxis
                : aliases.Length > 0 && addressGroup[0].Id != table.Id
                    ? XdfTableRole.DuplicateAlias
                    : XdfTableRole.Calibration;
            if (parents.Length > 0) evidence.Add($"Binary address is used by {parents.Length} parent map axis definition(s).");
            if (aliases.Length > 0) evidence.Add($"Binary address is shared by {aliases.Length} other definition(s).");

            var shape = table.RowCount > 1 && table.ColumnCount > 1
                ? XdfTableShape.Map
                : table.RowCount * table.ColumnCount == 1
                    ? XdfTableShape.Scalar
                    : XdfTableShape.Curve;
            evidence.Add($"Dimensions identify this item as a {shape.ToString().ToLowerInvariant()}.");

            var symbol = ExtractSymbol(table.Description);
            if (symbol is not null) evidence.Add($"ECU symbol extracted from the XDF description: {symbol}.");
            var (system, confidence, systemEvidence) = ClassifySystem(table, symbol);
            evidence.Add(systemEvidence);
            var displayTitle = BuildDisplayTitle(table, role, parents, source, axisOwners);
            var sourceClass = table.Flags switch
            {
                0x30 => "XDF 0x30 definition",
                0x0 => "XDF 0x0 definition",
                null when AutoGeneratedAxisTitle().IsMatch(table.Title) => "Generated axis definition",
                null => "Unflagged XDF definition",
                _ => $"XDF 0x{table.Flags:X} definition"
            };
            var searchParts = new[]
            {
                table.Title,
                displayTitle,
                table.Description,
                symbol,
                string.Join(' ', table.CategoryNames),
                system.ToString(),
                shape.ToString(),
                role.ToString(),
                sourceClass,
                table.ZAxis.Address.HasValue ? $"0x{table.ZAxis.Address.Value:X}" : null
            };
            var searchText = string.Join(' ', searchParts.Where(part => !string.IsNullOrWhiteSpace(part)));
            var sortKey = $"{(int)system:D3}|{(int)role:D2}|{displayTitle.ToUpperInvariant()}|{table.ZAxis.Address ?? long.MaxValue:D16}|{table.SourceIndex:D6}";

            classified[index] = table with
            {
                Identity = new XdfTableIdentity(
                    displayTitle,
                    symbol,
                    system,
                    shape,
                    role,
                    sourceClass,
                    confidence,
                    evidence,
                    parents,
                    aliases,
                    searchText,
                    sortKey)
            };
        }

        return classified;
    }

    public static XdfCalibrationSystem ClassifySystem(
        string title,
        string? description,
        IReadOnlyList<string> categoryNames,
        out double confidence,
        out string evidence)
    {
        var primaryProbe = string.Join(' ', new[] { title, description }
            .Where(value => !string.IsNullOrWhiteSpace(value))).ToLowerInvariant();
        var rules = SystemRules;
        foreach (var rule in rules)
        {
            if (!rule.Pattern.IsMatch(primaryProbe)) continue;
            confidence = rule.Confidence;
            evidence = $"Matched {rule.Label} terminology in the title, ECU symbol, or description.";
            return rule.System;
        }

        var categoryProbe = string.Join(' ', categoryNames).ToLowerInvariant();
        foreach (var rule in rules)
        {
            if (!rule.Pattern.IsMatch(categoryProbe)) continue;
            confidence = 0.68;
            evidence = $"Assigned from the original XDF category using {rule.Label} terminology.";
            return rule.System;
        }

        confidence = categoryNames.Count > 0 ? 0.45 : 0.2;
        evidence = categoryNames.Count > 0
            ? "No specialized system rule matched; original XDF categories are retained."
            : "No system terminology or category matched; review is required.";
        return XdfCalibrationSystem.Uncategorized;
    }

    public static XdfTableIdentity UnclassifiedIdentity(string title) => new(
        title,
        null,
        XdfCalibrationSystem.Uncategorized,
        XdfTableShape.Scalar,
        XdfTableRole.Calibration,
        "Unclassified",
        0,
        Array.Empty<string>(),
        Array.Empty<string>(),
        Array.Empty<string>(),
        title,
        title);

    private static Dictionary<long, AxisOwner[]> BuildAxisOwners(IReadOnlyList<XdfTableDefinition> source) =>
        source
            .SelectMany(table => new[]
            {
                table.XAxis.Address.HasValue ? new AxisOwner(table, "X", table.XAxis.Address.Value) : null,
                table.YAxis.Address.HasValue ? new AxisOwner(table, "Y", table.YAxis.Address.Value) : null
            })
            .Where(owner => owner is not null)
            .Cast<AxisOwner>()
            .GroupBy(owner => owner.Address)
            .ToDictionary(group => group.Key, group => group.ToArray());

    private static string BuildDisplayTitle(
        XdfTableDefinition table,
        XdfTableRole role,
        IReadOnlyList<string> parents,
        IReadOnlyList<XdfTableDefinition> source,
        IReadOnlyDictionary<long, AxisOwner[]> axisOwners)
    {
        if (role != XdfTableRole.BreakpointAxis || !table.ZAxis.Address.HasValue || parents.Count == 0)
        {
            return table.Title;
        }

        var owner = axisOwners[table.ZAxis.Address.Value]
            .OrderBy(candidate => candidate.Table.SourceIndex)
            .First();
        return $"{owner.Table.Title} - {owner.AxisId} axis breakpoint";
    }

    private static string? ExtractSymbol(string? description)
    {
        if (string.IsNullOrWhiteSpace(description)) return null;
        var firstLine = description.Trim().Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)[0].Trim();
        var separator = firstLine.IndexOf(" - ", StringComparison.Ordinal);
        var candidate = separator > 0 ? firstLine[..separator].Trim() : firstLine;
        return Symbol().IsMatch(candidate) ? candidate : null;
    }

    private static (XdfCalibrationSystem System, double Confidence, string Evidence) ClassifySystem(
        XdfTableDefinition table,
        string? symbol)
    {
        var description = string.Join(' ', new[] { table.Description, symbol }.Where(value => !string.IsNullOrWhiteSpace(value)));
        var system = ClassifySystem(table.Title, description, table.CategoryNames, out var confidence, out var evidence);
        return (system, confidence, evidence);
    }

    private sealed record AxisOwner(XdfTableDefinition Table, string AxisId, long Address);

    private sealed record SystemRule(XdfCalibrationSystem System, Regex Pattern, double Confidence, string Label);

    private static readonly SystemRule[] SystemRules =
    {
        Rule(XdfCalibrationSystem.OilPressure, @"\boil pressure\b|\bpoel", "oil-pressure"),
        Rule(XdfCalibrationSystem.PortInjection, @"\bport injection\b|\bpi idc\b|\breflex\b", "port-injection/ReFlex"),
        Rule(XdfCalibrationSystem.LowPressureFuel, @"\blpfp\b|\bekp\b|low.pressure fuel|electric fuel pump", "low-pressure-fuel/EKP"),
        Rule(XdfCalibrationSystem.HighPressureFuel, @"\bhpfp\b|\bhdp\b|\bhpp\b|rail pressure|high.pressure pump", "high-pressure-fuel/rail"),
        Rule(XdfCalibrationSystem.WastegateControl, @"\bwgdc\b|wastegate|turbine flow|turbine efficiency", "wastegate/turbine"),
        Rule(XdfCalibrationSystem.Boost, @"\bboost\b|ladedruck|pressure ratio|compressor map|chargepipe", "boost/compressor"),
        Rule(XdfCalibrationSystem.KnockControl, @"\bknock\b|klopf", "knock-control"),
        Rule(XdfCalibrationSystem.Ignition, @"\bignition\b|\btiming\b|spark|zuend|zünd|beginnwinkel|\bzw[_ -]", "ignition-angle"),
        Rule(XdfCalibrationSystem.DirectInjection, @"direct injection|injector|injection angle|injection pulse|injsys|injr", "direct-injection"),
        Rule(XdfCalibrationSystem.Fueling, @"\bfuel\b|lambda|air.?fuel|afr|stoich|enrichment|einspritz", "fuel/lambda"),
        Rule(XdfCalibrationSystem.Safeties, @"\bsafety\b|limp|failsafe|error code|overboost|bauteilschutz|component protection", "safety/limp/component-protection"),
        Rule(XdfCalibrationSystem.LaunchControl, @"launch control|racestart|anti.?lag|\bnls\b|no lift shift", "launch/antilag/NLS"),
        Rule(XdfCalibrationSystem.Torque, @"\btorque\b|\bpower\b|moment|drehmoment|\bmd[_ -]|trq|pwrcrk", "torque/power"),
        Rule(XdfCalibrationSystem.Throttle, @"\bthrottle\b|accel\.? pedal|drossel|mdk|wdk|ftransvl", "throttle/pedal"),
        Rule(XdfCalibrationSystem.Vanos, @"\bvanos\b|camshaft|cam timing|nockenwelle", "VANOS/camshaft"),
        Rule(XdfCalibrationSystem.RevLimits, @"rev limit|rpm limit|nmax|n_max", "engine-speed limit"),
        Rule(XdfCalibrationSystem.VehicleSpeedLimits, @"\bvmax\b|fahrgeschwindigkeit|speed limit", "vehicle-speed limit"),
        Rule(XdfCalibrationSystem.Idle, @"\bidle\b|\bstall(ing)?\b|leerlauf|\bllr\b", "idle/stall-control"),
        Rule(XdfCalibrationSystem.Transmission, @"transmission|gearbox|clutch|\bgear\b", "transmission/gear"),
        Rule(XdfCalibrationSystem.Cooling, @"\bcoolant\b|cooling|radiator|waterpump|fan pwm|luefter|lüfter", "cooling"),
        Rule(XdfCalibrationSystem.Exhaust, @"\bexhaust\b|\begt\b|catalyst|\bcat\b|burble", "exhaust/catalyst"),
        Rule(XdfCalibrationSystem.Airflow, @"\bmaf\b|air mass|airflow|luftmasse|volumetric efficiency", "airflow/MAF/volumetric-efficiency"),
        Rule(XdfCalibrationSystem.Sensors, @"\bsensor\b|signal check|tmapi?|map scaling|vrohmax", "sensor/calibration"),
        Rule(XdfCalibrationSystem.Load, @"\bload\b|\bfullung\b|\bfüllung\b|\brl[_ -]", "engine-load"),
        Rule(XdfCalibrationSystem.Instrumentation, @"performance gauge|performanceanzeige|perf display", "instrumentation/performance-gauge"),
        Rule(XdfCalibrationSystem.Configuration, @"\bconfig\b|\benable\b|\bdisable\b|\btoggle\b|map switch|codes list", "configuration/toggle"),
        Rule(XdfCalibrationSystem.WastegateControl, @"fupsrf|schluckgerade|ps_soll", "compressor-flow control")
    };

    private static SystemRule Rule(XdfCalibrationSystem system, string pattern, string label) =>
        new(system, new Regex(pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Compiled), 0.82, label);

    [GeneratedRegex(@" ([XY]) \(autogen\)$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex AutoGeneratedAxisTitle();

    [GeneratedRegex(@"^[A-Za-z][A-Za-z0-9_.$:#-]{2,}$", RegexOptions.CultureInvariant)]
    private static partial Regex Symbol();
}
