<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Redline.Calibration.Domain\Redline.Calibration.Domain.csproj" />
    <ProjectReference Include="..\..\src\Redline.Calibration.Binary\Redline.Calibration.Binary.csproj" />
    <ProjectReference Include="..\..\src\Redline.Calibration.Definitions.Xdf\Redline.Calibration.Definitions.Xdf.csproj" />
    <ProjectReference Include="..\..\src\Redline.Calibration.Logs\Redline.Calibration.Logs.csproj" />
    <ProjectReference Include="..\..\src\Redline.Calibration.Persistence\Redline.Calibration.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Redline.Calibration.Desktop\Redline.Calibration.Desktop.csproj" />
    <ProjectReference Include="..\..\src\Redline.Calibration.Diagnostics\Redline.Calibration.Diagnostics.csproj" />
  </ItemGroup>

</Project>
