[platformio]
default_envs = m5stamp_c3

[env:m5stamp_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DFW_VERSION=\"1.0.0\"
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.3
  bblanchon/ArduinoJson@^7.2.1
